### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by monib110** [GamesResearchTUG/HiCode#1]
Hi
Could you please help me with running your code?

**Comment by michaelholly** [comment]
Hi,
this project contains only the class structure for HiCode.
It should be sufficient to have a new .py file that includes this project and instantiates HiCode like
```
# read graph to neworkx graph, e.g. -> g

hicode = HiCode(g, <number of layers>)
hicode.run_layer_detection(<number of iterations for refinement>)
```

For further information please contact @M-Schiller

**Comment by monib110** [comment]
Thanks for your reply. Sent from Mail for Windows From: Michael Stefan HollySent: Wednesday, June 15, 2022 3:46 PMTo: GameLabGraz/HiCodeCc: mohadese; AuthorSubject: Re: [GameLabGraz/HiCode] How to run? (Issue #1) Hi,this project contains only the class structure for HiCode.It should be sufficient to have a new .py file that includes this project and instantiates HiCode like# read graph to neworkx graph, e.g. -> g hicode = HiCode(g, <number of layers>)hicode.run_layer_detection(<number of iterations for refinement>)For further information please contact @M-Schiller—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by M-Schiller** [comment]
As there has not been any activity in 8 weeks, I'll close this issue here.
